In [3]:
import numpy as np

In [4]:
x=np.zeros((3,4))

In [5]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
x=np.ones((2,3,4))

In [7]:
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
x=np.arange(10,25,5)

In [9]:
x

array([10, 15, 20])

In [10]:
x=np.linspace(0,2,9)

In [11]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
x=np.full((2,2),7)

In [13]:
x

array([[7, 7],
       [7, 7]])

In [14]:
x=np.random.random((2,2))

In [15]:
x

array([[0.45193225, 0.66796258],
       [0.50201457, 0.16772006]])

In [16]:
x=np.eye(2,2)

In [17]:
x

array([[1., 0.],
       [0., 1.]])

In [18]:
x=np.array(((1,2,3),
            (4,5,6)))

In [19]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
x_T = np.transpose(x)

In [22]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
x_T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
x=a+b 

In [25]:
x

array([5, 7, 9])

In [26]:
a=np.array([1,2,3,4,5,6])
x=np.split(a,2)

In [27]:
x

[array([1, 2, 3]), array([4, 5, 6])]